## Introduction
- Pandas: a framework to manipulate tabular data

### Install
- pip install pandas
- uv add pandas

In [5]:
%pip install pandas --quiet
#!uv pip install pandas --quiet
#!pip install pandas --quiet

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: /usr/local/Cellar/jupyterlab/4.2.5_1/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd

print(pd.__version__)

3.0.6

### Pandas DataFrame
- is like a table with rows and columns

In [11]:
student = pd.DataFrame({'age': [20, 50, 90, 37], 'names': ['J', 'M','B', 'G']})

student

   age names
0   20     J
1   50     M
2   90     B
3   37     G

## Pandas Series
- Its a one-dimensional labeled data

In [12]:
ages = pd.Series([20, 50, 90, 37])
ages

0    20
1    50
2    90
3    37
dtype: int64

## Create a dataframe from dictionary

In [15]:
data = {
    "Name": ["John", "Mary", "David"],
    "Age": [22, 25, 30],
    "temperature": [98.6, 99.1, 97.5],
    "City": ["Accra", "Houston", "Toronto"], 
    "Location": ["Ghana", "USA", "Canada"],
    "Occupation": ["Engineer", "Doctor", "Artist"]
}

df = pd.DataFrame(data)

df

    Name  Age  temperature     City Location Occupation
0   John   22         98.6    Accra    Ghana   Engineer
1   Mary   25         99.1  Houston      USA     Doctor
2  David   30         97.5  Toronto   Canada     Artist

## View Data

`object = ClassName()`;
`object.function_name()`

In [17]:
df.head(2)

   Name  Age  temperature     City Location Occupation
0  John   22         98.6    Accra    Ghana   Engineer
1  Mary   25         99.1  Houston      USA     Doctor

In [21]:
df.tail(1)

    Name  Age  temperature     City Location Occupation
2  David   30         97.5  Toronto   Canada     Artist

## Data Information

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         3 non-null      str
 1   Age          3 non-null      int64
 2   temperature  3 non-null      float64
 3   City         3 non-null      str
 4   Location     3 non-null      str
 5   Occupation   3 non-null      str
dtypes: float64(1), int64(1), str(4)
memory usage: 276.0 bytes

## Statistical Summary

In [23]:
df.describe()

             Age  temperature
count   3.000000     3.000000
mean   25.666667    98.400000
std     4.041452     0.818535
min    22.000000    97.500000
25%    23.500000    98.050000
50%    25.000000    98.600000
75%    27.500000    98.850000
max    30.000000    99.100000

## Selecting columns, or single column

In [24]:
df

    Name  Age  temperature     City Location Occupation
0   John   22         98.6    Accra    Ghana   Engineer
1   Mary   25         99.1  Houston      USA     Doctor
2  David   30         97.5  Toronto   Canada     Artist

In [28]:
df['Age'] + 10

0    32
1    35
2    40
Name: Age, dtype: int64

In [27]:
df.Age + 10

0    32
1    35
2    40
Name: Age, dtype: int64

In [31]:
col_names = ['Age', 'City', 'temperature']

df[col_names]

# df[['Age', 'City', 'temperature']]

   Age     City  temperature
0   22    Accra         98.6
1   25  Houston         99.1
2   30  Toronto         97.5

## Checking column names in a dataframe

In [34]:
# df.columns

for col in df.columns:
    print(col)

Name
Age
temperature
City
Location
Occupation

In [37]:
[col for col in df.columns] # list comprehension

['Name', 'Age', 'temperature', 'City', 'Location', 'Occupation']

## Filtering data

In [38]:
df

    Name  Age  temperature     City Location Occupation
0   John   22         98.6    Accra    Ghana   Engineer
1   Mary   25         99.1  Houston      USA     Doctor
2  David   30         97.5  Toronto   Canada     Artist

In [39]:
df['City']

0      Accra
1    Houston
2    Toronto
Name: City, dtype: str

In [43]:
# those living in Houston
df[ df['City'] == 'Houston' ]

   Name  Age  temperature     City Location Occupation
1  Mary   25         99.1  Houston      USA     Doctor

In [42]:
# those not living in Houston
df[ df['City'] != 'Houston' ]

    Name  Age  temperature     City Location Occupation
0   John   22         98.6    Accra    Ghana   Engineer
2  David   30         97.5  Toronto   Canada     Artist

In [45]:
# | means OR, & means AND

df[ (df['City'] == 'Accra') | (df['Age'] <= 25) ]

   Name  Age  temperature     City Location Occupation
0  John   22         98.6    Accra    Ghana   Engineer
1  Mary   25         99.1  Houston      USA     Doctor

In [46]:
df[ (df['City'] == 'Accra') & (df['Age'] <= 25) ]

   Name  Age  temperature   City Location Occupation
0  John   22         98.6  Accra    Ghana   Engineer

## Adding a new column