## Introduction
- Pandas: a framework to manipulate tabular data

### Install
- pip install pandas
- uv add pandas

In [1]:
%pip install pandas --quiet
#!uv pip install pandas --quiet
#!pip install pandas --quiet

Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

print(pd.__version__)

3.0.6

### Pandas DataFrame
- is like a table with rows and columns

In [3]:
student = pd.DataFrame({'age': [20, 50, 90, 37], 'names': ['J', 'M','B', 'G']})

student

   age names
0   20     J
1   50     M
2   90     B
3   37     G

## Pandas Series
- Its a one-dimensional labeled data

In [4]:
ages = pd.Series([20, 50, 90, 37])
ages

0    20
1    50
2    90
3    37
dtype: int64

## Create a dataframe from dictionary

In [5]:
data = {
    "Name": ["John", "Mary", "David"],
    "Age": [22, 25, 30],
    "temperature": [98.6, 99.1, 97.5],
    "City": ["Accra", "Houston", "Toronto"], 
    "Location": ["Ghana", "USA", "Canada"],
    "Occupation": ["Engineer", "Doctor", "Artist"]
}

df = pd.DataFrame(data)

df

    Name  Age  temperature     City Location Occupation
0   John   22         98.6    Accra    Ghana   Engineer
1   Mary   25         99.1  Houston      USA     Doctor
2  David   30         97.5  Toronto   Canada     Artist

## View Data

`object = ClassName()`;
`object.function_name()`

In [6]:
df.head(2)

   Name  Age  temperature     City Location Occupation
0  John   22         98.6    Accra    Ghana   Engineer
1  Mary   25         99.1  Houston      USA     Doctor

In [7]:
df.tail(1)

    Name  Age  temperature     City Location Occupation
2  David   30         97.5  Toronto   Canada     Artist

## Data Information

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         3 non-null      str
 1   Age          3 non-null      int64
 2   temperature  3 non-null      float64
 3   City         3 non-null      str
 4   Location     3 non-null      str
 5   Occupation   3 non-null      str
dtypes: float64(1), int64(1), str(4)
memory usage: 276.0 bytes

## Statistical Summary

In [9]:
df.describe()

             Age  temperature
count   3.000000     3.000000
mean   25.666667    98.400000
std     4.041452     0.818535
min    22.000000    97.500000
25%    23.500000    98.050000
50%    25.000000    98.600000
75%    27.500000    98.850000
max    30.000000    99.100000

## Selecting columns, or single column

In [10]:
df

    Name  Age  temperature     City Location Occupation
0   John   22         98.6    Accra    Ghana   Engineer
1   Mary   25         99.1  Houston      USA     Doctor
2  David   30         97.5  Toronto   Canada     Artist

In [11]:
df['Age'] + 10

0    32
1    35
2    40
Name: Age, dtype: int64

In [12]:
df.Age + 10

0    32
1    35
2    40
Name: Age, dtype: int64

In [13]:
col_names = ['Age', 'City', 'temperature']

df[col_names]

# df[['Age', 'City', 'temperature']]

   Age     City  temperature
0   22    Accra         98.6
1   25  Houston         99.1
2   30  Toronto         97.5

## Checking column names in a dataframe

In [14]:
# df.columns

for col in df.columns:
    print(col)

Name
Age
temperature
City
Location
Occupation

In [15]:
[col for col in df.columns] # list comprehension

['Name', 'Age', 'temperature', 'City', 'Location', 'Occupation']

## Filtering data

In [16]:
df

    Name  Age  temperature     City Location Occupation
0   John   22         98.6    Accra    Ghana   Engineer
1   Mary   25         99.1  Houston      USA     Doctor
2  David   30         97.5  Toronto   Canada     Artist

In [17]:
df['City']

0      Accra
1    Houston
2    Toronto
Name: City, dtype: str

In [18]:
# those living in Houston
df[ df['City'] == 'Houston' ]

   Name  Age  temperature     City Location Occupation
1  Mary   25         99.1  Houston      USA     Doctor

In [19]:
# those not living in Houston
df[ df['City'] != 'Houston' ]

    Name  Age  temperature     City Location Occupation
0   John   22         98.6    Accra    Ghana   Engineer
2  David   30         97.5  Toronto   Canada     Artist

In [20]:
# | means OR, & means AND

df[ (df['City'] == 'Accra') | (df['Age'] <= 25) ]

   Name  Age  temperature     City Location Occupation
0  John   22         98.6    Accra    Ghana   Engineer
1  Mary   25         99.1  Houston      USA     Doctor

In [21]:
df[ (df['City'] == 'Accra') & (df['Age'] <= 25) ]

   Name  Age  temperature   City Location Occupation
0  John   22         98.6  Accra    Ghana   Engineer

## Adding a new column

In [22]:
df

    Name  Age  temperature     City Location Occupation
0   John   22         98.6    Accra    Ghana   Engineer
1   Mary   25         99.1  Houston      USA     Doctor
2  David   30         97.5  Toronto   Canada     Artist

In [23]:
df['Passed'] = df['Age'] >= 25

df

    Name  Age  temperature     City Location Occupation  Passed
0   John   22         98.6    Accra    Ghana   Engineer   False
1   Mary   25         99.1  Houston      USA     Doctor    True
2  David   30         97.5  Toronto   Canada     Artist    True

### Remove/Drop columns

In [24]:
df.drop('Passed', axis=1, inplace=True)

In [25]:
df

    Name  Age  temperature     City Location Occupation
0   John   22         98.6    Accra    Ghana   Engineer
1   Mary   25         99.1  Houston      USA     Doctor
2  David   30         97.5  Toronto   Canada     Artist

In [26]:
df.drop(['Occupation', 'City'], axis=1, inplace=True)

df

    Name  Age  temperature Location
0   John   22         98.6    Ghana
1   Mary   25         99.1      USA
2  David   30         97.5   Canada

### Handling Missing Values

In [27]:
data = {
    "Name": ["John", "Mary", None],
    "Score": [85, None, 90]
}

df = pd.DataFrame(data)

df

   Name  Score
0  John   85.0
1  Mary    NaN
2   NaN   90.0

In [28]:
# checking if there are missing values in your dataset

df.isnull()

    Name  Score
0  False  False
1  False   True
2   True  False

### Remove missing values

In [29]:
df.dropna()

   Name  Score
0  John   85.0

In [30]:
# fill the missing values with zeros

df = df.fillna(0)
df

   Name  Score
0  John   85.0
1  Mary    0.0
2     0   90.0

In [31]:
df['Score'] = df['Score'].fillna(0)
df

   Name  Score
0  John   85.0
1  Mary    0.0
2     0   90.0

In [32]:
df['Name'] = df['Name'].fillna("Unknow")
df

   Name  Score
0  John   85.0
1  Mary    0.0
2     0   90.0

### Sort the data by score column ascending/descending order

In [33]:
sort_df = df.sort_values(['Score'], ascending=False)
sort_df

   Name  Score
2     0   90.0
0  John   85.0
1  Mary    0.0

###  Grouping Data

In [34]:
data = {
    "Department": ["IT", "HR", "IT", "Finance"],
    "Salary": [5000, 4000, 6000, 4500]
}

df = pd.DataFrame(data)

df

  Department  Salary
0         IT    5000
1         HR    4000
2         IT    6000
3    Finance    4500

In [35]:
# give me the average salary by department

avg_df = df.groupby("Department")['Salary'].mean()
avg_df

Department
Finance    4500.0
HR         4000.0
IT         5500.0
Name: Salary, dtype: float64

### Save to .csv

In [36]:
avg_df.to_csv("department_salary.csv", index=True)

### Save to .xlsx
- pip install openpyxl

In [37]:
%pip install openpyxl --quiet

Note: you may need to restart the kernel to use updated packages.

In [38]:
avg_df.to_excel("department_salary.xlsx", index=True)

In [39]:
avg_df.to_json("department_salary.json")

### Student Data

In [40]:
students = {
    "Name": ["John", "Mary", "David", "Sarah"],
    "Math": [80, 95, 70, 88],
    "Science": [85, 90, 75, 92]
}

df = pd.DataFrame(students)

df

    Name  Math  Science
0   John    80       85
1   Mary    95       90
2  David    70       75
3  Sarah    88       92

In [41]:
df['average_score'] = (df['Math'] + df['Science']) / 2

# find those who failed or passed with an average score of 75%
df['Passed'] = df['average_score'] >= 75

df

    Name  Math  Science  average_score  Passed
0   John    80       85           82.5    True
1   Mary    95       90           92.5    True
2  David    70       75           72.5   False
3  Sarah    88       92           90.0    True

### Create a function and apply it to the average column

In [42]:
# using this function approach

def determine_pass_fail(avg_score):
    if avg_score >= 75:
        return "Passed"
    else:
        return "Failed"


# using lambda approach (HOME WORK)

df['Status'] = df['average_score'].apply(determine_pass_fail)

In [43]:
df

    Name  Math  Science  average_score  Passed  Status
0   John    80       85           82.5    True  Passed
1   Mary    95       90           92.5    True  Passed
2  David    70       75           72.5   False  Failed
3  Sarah    88       92           90.0    True  Passed

In [44]:
df.to_csv("avg_score.csv", index=True)

### Merging DataFrames

In [45]:
students = pd.DataFrame({
    "StudentID": [1, 2, 3],
    "Name": ["John", "Mary", "David"]
})

students

   StudentID   Name
0          1   John
1          2   Mary
2          3  David

In [46]:
scores = pd.DataFrame({
    "StudentID": [1, 2, 4],
    "Score": [85, 90, 75]
})

scores

   StudentID  Score
0          1     85
1          2     90
2          4     75

In [47]:
# type of joins: left, right, outer, inner, cross

merged_df = pd.merge(students, scores, on="StudentID", how="outer")
merged_df

   StudentID   Name  Score
0          1   John   85.0
1          2   Mary   90.0
2          3  David    NaN
3          4    NaN   75.0

In [48]:
df1 = pd.DataFrame({
    "Name": ["John", "Mary"],
    "City": ["Accra", "Kumasi"],
    "Age": [25, 30]
})

df2 = pd.DataFrame({
    "Name": ["John", "Mary"],
    "City": ["Accra", "Kumasi"],
    "Salary": [5000, 7000]
})

In [49]:
df1

   Name    City  Age
0  John   Accra   25
1  Mary  Kumasi   30

In [50]:
df2

   Name    City  Salary
0  John   Accra    5000
1  Mary  Kumasi    7000

In [51]:
pd.merge(df1, df2, on=["Name", "City"], how="inner")

   Name    City  Age  Salary
0  John   Accra   25    5000
1  Mary  Kumasi   30    7000

### Concatenation

In [52]:
# january sales data

jan_sales = pd.DataFrame({
    "Product": ["Laptop", "Mouse"],
    "Sales": [10, 50]
})

jan_sales

  Product  Sales
0  Laptop     10
1   Mouse     50

In [53]:
# february sales data

feb_sales = pd.DataFrame({
    "Product": ["Keyboard", "Monitor"],
    "Sales": [20, 15]
})

feb_sales

    Product  Sales
0  Keyboard     20
1   Monitor     15

In [54]:
jan_feb_sales = pd.concat([jan_sales, feb_sales], ignore_index=True)
jan_feb_sales

    Product  Sales
0    Laptop     10
1     Mouse     50
2  Keyboard     20
3   Monitor     15

### Wine Data

In [55]:
# pd.read_json(), pd.read_excel(), ...

wine_df = pd.read_csv("wine.csv")

wine_df

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [56]:
wine_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Wine                  178 non-null    int64
 1   Alcohol               178 non-null    float64
 2   Malic.acid            178 non-null    float64
 3   Ash                   178 non-null    float64
 4   Acl                   178 non-null    float64
 5   Mg                    178 non-null    int64
 6   Phenols               178 non-null    float64
 7   Flavanoids            178 non-null    float64
 8   Nonflavanoid.phenols  178 non-null    float64
 9   Proanth               178 non-null    float64
 10  Color.int             178 non-null    float64
 11  Hue                   178 non-null    float64
 12  OD                    178 non-null    float64
 13  Proline               178 non-null    int64
dtypes: float64(11), int64(3)
memory usage: 19.6 KB

In [57]:
wine_df.columns

Index(['Wine', 'Alcohol', 'Malic.acid', 'Ash', 'Acl', 'Mg', 'Phenols',
       'Flavanoids', 'Nonflavanoid.phenols', 'Proanth', 'Color.int', 'Hue',
       'OD', 'Proline'],
      dtype='str')

In [58]:
wine_df.describe()

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,1.938202,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258
std,0.775035,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474
min,1.000000,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000
25%,1.000000,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000
50%,2.000000,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000
75%,3.000000,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000
max,3.000000,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000

In [59]:
wine_df['Wine'].value_counts()

Wine
2    71
1    59
3    48
Name: count, dtype: int64

In [60]:
wine_df.head(3)

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185

In [61]:
wine_df.tail(3)

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.2,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.3,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.2,0.61,1.60,560

In [62]:
wine_df[['Wine', 'Ash', 'Acl']]

     Wine   Ash   Acl
0       1  2.43  15.6
1       1  2.14  11.2
2       1  2.67  18.6
3       1  2.50  16.8
4       1  2.87  21.0
..    ...   ...   ...
173     3  2.45  20.5
174     3  2.48  23.0
175     3  2.26  20.0
176     3  2.37  20.0
177     3  2.74  24.5

[178 rows x 3 columns]

In [63]:
new_df = wine_df[wine_df['Wine'] == 3]

new_df.to_csv("all_threes.csv", index=True)

In [64]:
wine_df[["Ash", "Acl"]].describe()

              Ash         Acl
count  178.000000  178.000000
mean     2.366517   19.494944
std      0.274344    3.339564
min      1.360000   10.600000
25%      2.210000   17.200000
50%      2.360000   19.500000
75%      2.557500   21.500000
max      3.230000   30.000000

In [65]:
wine_df[["Ash", "Acl"]].median()

Ash     2.36
Acl    19.50
dtype: float64

In [66]:
wine_df.agg({"Ash": ["min", "max", "median", "skew"],"Acl": ["min", "max", "median", "mean"],})

             Ash        Acl
min     1.360000  10.600000
max     3.230000  30.000000
median  2.360000  19.500000
skew   -0.176699        NaN
mean         NaN  19.494944

### Read Titanic dataset

In [67]:
titanic = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [68]:
air_quality = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/refs/heads/main/doc/data/air_quality_long.csv")

air_quality

,city,country,date.utc,location,parameter,value,unit
0,Antwerpen,BE,2019-06-18 06:00:00+00:00,BETR801,pm25,18.0,µg/m³
1,Antwerpen,BE,2019-06-17 08:00:00+00:00,BETR801,pm25,6.5,µg/m³
2,Antwerpen,BE,2019-06-17 07:00:00+00:00,BETR801,pm25,18.5,µg/m³
3,Antwerpen,BE,2019-06-17 06:00:00+00:00,BETR801,pm25,16.0,µg/m³
4,Antwerpen,BE,2019-06-17 05:00:00+00:00,BETR801,pm25,7.5,µg/m³
...,...,...,...,...,...,...,...
5267,London,GB,2019-04-09 06:00:00+00:00,London Westminster,no2,41.0,µg/m³
5268,London,GB,2019-04-09 05:00:00+00:00,London Westminster,no2,41.0,µg/m³
5269,London,GB,2019-04-09 04:00:00+00:00,London Westminster,no2,41.0,µg/m³
5270,London,GB,2019-04-09 03:00:00+00:00,London Westminster,no2,67.0,µg/m³
5271,London,GB,2019-04-09 02:00:00+00:00,London Westminster,no2,67.0,µg/m³

In [69]:
titanic['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

### More Pandas

In [94]:
import pandas as pd
import numpy as np

np.random.seed(42)

df = pd.DataFrame({
    "customer_id": np.random.choice(
        ["C001", "C002", "C003", "C004", "C005"],
        20
    ),
    "region": np.random.choice(
        ["North", "South", "East", "West"],
        20
    ),
    "product": np.random.choice(
        ["Laptop", "Phone", "Tablet", "Monitor"],
        20
    ),
    "quantity": np.random.randint(1, 6, 20),
    "price": np.random.choice(
        [299, 499, 799, 999, 1299],
        20
    ),
    "date": pd.date_range(
        "2026-01-01",
        periods=20,
        freq="D"
    )
})

df

   customer_id region  product  quantity  price       date
0         C004  South  Monitor         2    499 2026-01-01
1         C005  South   Tablet         5    499 2026-01-02
2         C003  North  Monitor         2    999 2026-01-03
3         C005   West  Monitor         4    999 2026-01-04
4         C005  North   Laptop         4    299 2026-01-05
5         C002  North   Tablet         4   1299 2026-01-06
6         C003   East   Laptop         4   1299 2026-01-07
7         C003   East   Tablet         5    499 2026-01-08
8         C003   East   Tablet         3   1299 2026-01-09
9         C005  South   Laptop         1    499 2026-01-10
10        C004   West   Laptop         4    299 2026-01-11
11        C003   West   Tablet         2    999 2026-01-12
12        C005   West    Phone         4    999 2026-01-13
13        C002   West  Monitor         2    999 2026-01-14
14        C004   East   Laptop         2   1299 2026-01-15
15        C002  South  Monitor         4    299 2026-01-16
16        C004  South    Phone         5   1299 2026-01-17
17        C005   East    Phone         2   1299 2026-01-18
18        C001  South    Phone         2    299 2026-01-19
19        C004   East   Laptop         4    299 2026-01-20

In [96]:
df['revenue'] = df['quantity'] * df['price']
df

   customer_id region  product  quantity  price       date  revenue
0         C004  South  Monitor         2    499 2026-01-01      998
1         C005  South   Tablet         5    499 2026-01-02     2495
2         C003  North  Monitor         2    999 2026-01-03     1998
3         C005   West  Monitor         4    999 2026-01-04     3996
4         C005  North   Laptop         4    299 2026-01-05     1196
5         C002  North   Tablet         4   1299 2026-01-06     5196
6         C003   East   Laptop         4   1299 2026-01-07     5196
7         C003   East   Tablet         5    499 2026-01-08     2495
8         C003   East   Tablet         3   1299 2026-01-09     3897
9         C005  South   Laptop         1    499 2026-01-10      499
10        C004   West   Laptop         4    299 2026-01-11     1196
11        C003   West   Tablet         2    999 2026-01-12     1998
12        C005   West    Phone         4    999 2026-01-13     3996
13        C002   West  Monitor         2    999 2026-01-14     1998
14        C004   East   Laptop         2   1299 2026-01-15     2598
15        C002  South  Monitor         4    299 2026-01-16     1196
16        C004  South    Phone         5   1299 2026-01-17     6495
17        C005   East    Phone         2   1299 2026-01-18     2598
18        C001  South    Phone         2    299 2026-01-19      598
19        C004   East   Laptop         4    299 2026-01-20     1196

In [74]:
df[
    (df['quantity'] > 2) & (df['revenue'] > 1000)
]

   customer_id region  product  quantity  price       date  revenue
1         C005  South   Tablet         5    499 2026-01-02     2495
3         C005   West  Monitor         4    999 2026-01-04     3996
4         C005  North   Laptop         4    299 2026-01-05     1196
5         C002  North   Tablet         4   1299 2026-01-06     5196
6         C003   East   Laptop         4   1299 2026-01-07     5196
7         C003   East   Tablet         5    499 2026-01-08     2495
8         C003   East   Tablet         3   1299 2026-01-09     3897
10        C004   West   Laptop         4    299 2026-01-11     1196
12        C005   West    Phone         4    999 2026-01-13     3996
15        C002  South  Monitor         4    299 2026-01-16     1196
16        C004  South    Phone         5   1299 2026-01-17     6495
19        C004   East   Laptop         4    299 2026-01-20     1196

In [75]:
df.query("quantity > 2 and revenue > 1000")

   customer_id region  product  quantity  price       date  revenue
1         C005  South   Tablet         5    499 2026-01-02     2495
3         C005   West  Monitor         4    999 2026-01-04     3996
4         C005  North   Laptop         4    299 2026-01-05     1196
5         C002  North   Tablet         4   1299 2026-01-06     5196
6         C003   East   Laptop         4   1299 2026-01-07     5196
7         C003   East   Tablet         5    499 2026-01-08     2495
8         C003   East   Tablet         3   1299 2026-01-09     3897
10        C004   West   Laptop         4    299 2026-01-11     1196
12        C005   West    Phone         4    999 2026-01-13     3996
15        C002  South  Monitor         4    299 2026-01-16     1196
16        C004  South    Phone         5   1299 2026-01-17     6495
19        C004   East   Laptop         4    299 2026-01-20     1196

In [76]:
df.query("quantity >= 2 and price >=500 and region == 'North' ")

  customer_id region  product  quantity  price       date  revenue
2        C003  North  Monitor         2    999 2026-01-03     1998
5        C002  North   Tablet         4   1299 2026-01-06     5196

In [78]:
df[
    (df['quantity'] >= 2) & (df['price'] >= 500) & (df['region'].isin(['North', 'West']))
]

   customer_id region  product  quantity  price       date  revenue
2         C003  North  Monitor         2    999 2026-01-03     1998
3         C005   West  Monitor         4    999 2026-01-04     3996
5         C002  North   Tablet         4   1299 2026-01-06     5196
11        C003   West   Tablet         2    999 2026-01-12     1998
12        C005   West    Phone         4    999 2026-01-13     3996
13        C002   West  Monitor         2    999 2026-01-14     1998

### Conditional columns with np.where()

In [79]:
df['order_type'] = np.where(df['revenue'] >= 2000, "High", "Low")
df

   customer_id region  product  quantity  price       date  revenue order_type
0         C004  South  Monitor         2    499 2026-01-01      998        Low
1         C005  South   Tablet         5    499 2026-01-02     2495       High
2         C003  North  Monitor         2    999 2026-01-03     1998        Low
3         C005   West  Monitor         4    999 2026-01-04     3996       High
4         C005  North   Laptop         4    299 2026-01-05     1196        Low
5         C002  North   Tablet         4   1299 2026-01-06     5196       High
6         C003   East   Laptop         4   1299 2026-01-07     5196       High
7         C003   East   Tablet         5    499 2026-01-08     2495       High
8         C003   East   Tablet         3   1299 2026-01-09     3897       High
9         C005  South   Laptop         1    499 2026-01-10      499        Low
10        C004   West   Laptop         4    299 2026-01-11     1196        Low
11        C003   West   Tablet         2    999 2026-01-12     1998        Low
12        C005   West    Phone         4    999 2026-01-13     3996       High
13        C002   West  Monitor         2    999 2026-01-14     1998        Low
14        C004   East   Laptop         2   1299 2026-01-15     2598       High
15        C002  South  Monitor         4    299 2026-01-16     1196        Low
16        C004  South    Phone         5   1299 2026-01-17     6495       High
17        C005   East    Phone         2   1299 2026-01-18     2598       High
18        C001  South    Phone         2    299 2026-01-19      598        Low
19        C004   East   Laptop         4    299 2026-01-20     1196        Low

# sql
SELECT region, SUM(revenue)
FROM transactions
GROUP BY region

In [81]:
pd.DataFrame(
    df.groupby("region")['revenue'].sum()
)

        revenue
region
East      17980
North      8390
South     12281
West      13184

In [83]:
pd.DataFrame(
    df.groupby("region")['revenue'].agg(["sum","min", "max", "mean","std", "count"])

          sum   min   max         mean          std  count
region
East    17980  1196  5196  2996.666667  1375.471362      6
North    8390  1196  5196  2796.666667  2116.223366      3
South   12281   499  6495  2046.833333  2293.726873      6
West    13184  1196  3996  2636.800000  1283.246352      5

In [85]:
pd.DataFrame(
    df.groupby("region").agg(total_revenue=("revenue", "sum"),
                             average_revenue=("revenue", "mean"), 
                             total_quantity=("quantity", "sum"))
)

        total_revenue  average_revenue  total_quantity
region
East            17980      2996.666667              20
North            8390      2796.666667              10
South           12281      2046.833333              19
West            13184      2636.800000              16

### how do you check for duplicates in your dataset

In [87]:
# set()
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

### how do you remove duplicates in your dataset

In [88]:
df.drop_duplicates()

   customer_id region  product  quantity  price       date  revenue order_type
0         C004  South  Monitor         2    499 2026-01-01      998        Low
1         C005  South   Tablet         5    499 2026-01-02     2495       High
2         C003  North  Monitor         2    999 2026-01-03     1998        Low
3         C005   West  Monitor         4    999 2026-01-04     3996       High
4         C005  North   Laptop         4    299 2026-01-05     1196        Low
5         C002  North   Tablet         4   1299 2026-01-06     5196       High
6         C003   East   Laptop         4   1299 2026-01-07     5196       High
7         C003   East   Tablet         5    499 2026-01-08     2495       High
8         C003   East   Tablet         3   1299 2026-01-09     3897       High
9         C005  South   Laptop         1    499 2026-01-10      499        Low
10        C004   West   Laptop         4    299 2026-01-11     1196        Low
11        C003   West   Tablet         2    999 2026-01-12     1998        Low
12        C005   West    Phone         4    999 2026-01-13     3996       High
13        C002   West  Monitor         2    999 2026-01-14     1998        Low
14        C004   East   Laptop         2   1299 2026-01-15     2598       High
15        C002  South  Monitor         4    299 2026-01-16     1196        Low
16        C004  South    Phone         5   1299 2026-01-17     6495       High
17        C005   East    Phone         2   1299 2026-01-18     2598       High
18        C001  South    Phone         2    299 2026-01-19      598        Low
19        C004   East   Laptop         4    299 2026-01-20     1196        Low

In [89]:
df = pd.DataFrame(
...     {
...         "brand": ["Yum Yum", "Yum Yum", "Indomie", "Indomie", "Indomie"],
...         "style": ["cup", "cup", "cup", "pack", "pack"],
...         "rating": [4, 4, 3.5, 15, 5],
...     }
... )

df

     brand style  rating
0  Yum Yum   cup     4.0
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

In [90]:
df.drop_duplicates()

     brand style  rating
0  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

In [91]:
df.drop_duplicates(subset=["brand", "style"], keep="last")

     brand style  rating
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
4  Indomie  pack     5.0

### Pivot Table
- suppose we want revenue by region and product

In [101]:
pvt = pd.pivot_table(
    df,
    values="revenue",
    index="region",
    columns="product",
    aggfunc="sum",
    fill_value=0
)

pvt

product  Laptop  Monitor  Phone  Tablet
region
East       8990        0   2598    6392
North      1196     1998      0    5196
South       499     2194   7093    2495
West       1196     5994   3996    1998

In [102]:
pvt.T

region   East  North  South  West
product
Laptop   8990   1196    499  1196
Monitor     0   1998   2194  5994
Phone    2598      0   7093  3996
Tablet   6392   5196   2495  1998

### lambda application
- calculate tax on the revenue 8%
- df['tax'] = df['revenue'] * 0.08

In [103]:
df['tax'] = df['revenue'].apply(lambda x: x * 0.08)
df

   customer_id region  product  quantity  price       date  revenue     tax
0         C004  South  Monitor         2    499 2026-01-01      998   79.84
1         C005  South   Tablet         5    499 2026-01-02     2495  199.60
2         C003  North  Monitor         2    999 2026-01-03     1998  159.84
3         C005   West  Monitor         4    999 2026-01-04     3996  319.68
4         C005  North   Laptop         4    299 2026-01-05     1196   95.68
5         C002  North   Tablet         4   1299 2026-01-06     5196  415.68
6         C003   East   Laptop         4   1299 2026-01-07     5196  415.68
7         C003   East   Tablet         5    499 2026-01-08     2495  199.60
8         C003   East   Tablet         3   1299 2026-01-09     3897  311.76
9         C005  South   Laptop         1    499 2026-01-10      499   39.92
10        C004   West   Laptop         4    299 2026-01-11     1196   95.68
11        C003   West   Tablet         2    999 2026-01-12     1998  159.84
12        C005   West    Phone         4    999 2026-01-13     3996  319.68
13        C002   West  Monitor         2    999 2026-01-14     1998  159.84
14        C004   East   Laptop         2   1299 2026-01-15     2598  207.84
15        C002  South  Monitor         4    299 2026-01-16     1196   95.68
16        C004  South    Phone         5   1299 2026-01-17     6495  519.60
17        C005   East    Phone         2   1299 2026-01-18     2598  207.84
18        C001  South    Phone         2    299 2026-01-19      598   47.84
19        C004   East   Laptop         4    299 2026-01-20     1196   95.68

In [106]:
tax = lambda x: x * 0.08
tax(998)

79.84

In [107]:
df["total"] = df["revenue"] + df["tax"]
df

,customer_id,region,product,quantity,price,date,revenue,tax,total
0,C004,South,Monitor,2,499,2026-01-01,998,79.84,1077.84
1,C005,South,Tablet,5,499,2026-01-02,2495,199.60,2694.60
2,C003,North,Monitor,2,999,2026-01-03,1998,159.84,2157.84
3,C005,West,Monitor,4,999,2026-01-04,3996,319.68,4315.68
4,C005,North,Laptop,4,299,2026-01-05,1196,95.68,1291.68
5,C002,North,Tablet,4,1299,2026-01-06,5196,415.68,5611.68
6,C003,East,Laptop,4,1299,2026-01-07,5196,415.68,5611.68
7,C003,East,Tablet,5,499,2026-01-08,2495,199.60,2694.60
8,C003,East,Tablet,3,1299,2026-01-09,3897,311.76,4208.76
9,C005,South,Laptop,1,499,2026-01-10,499,39.92,538.92
10,C004,West,Laptop,4,299,2026-01-11,1196,95.68,1291.68
11,C003,West,Tablet,2,999,2026-01-12,1998,159.84,2157.84
12,C005,West,Phone,4,999,2026-01-13,3996,319.68,4315.68
13,C002,West,Monitor,2,999,2026-01-14,1998,159.84,2157.84
14,C004,East,Laptop,2,1299,2026-01-15,2598,207.84,2805.84
15,C002,South,Monitor,4,299,2026-01-16,1196,95.68,1291.68
16,C004,South,Phone,5,1299,2026-01-17,6495,519.60,7014.60
17,C005,East,Phone,2,1299,2026-01-18,2598,207.84,2805.84
18,C001,South,Phone,2,299,2026-01-19,598,47.84,645.84
19,C004,East,Laptop,4,299,2026-01-20,1196,95.68,1291.68

In [108]:
df.to_csv("products.csv", index=True)

### Assign() for pipelines

In [ ]:
df["revenue"] = df["quantity"] * df["price"]
df['tax'] = df['revenue'].apply(lambda x: x * 0.08)
df["total"] = df["revenue"] + df["tax"]

In [110]:
result = df.assign(
    revenue_new=lambda x: x['quantity'] * x['price'],
    tax_new=lambda x: x['revenue'] * 0.08,
    total_new=lambda x: x['revenue'] + x['tax']
)

result

,customer_id,region,product,quantity,price,date,revenue,tax,total,revenue_new,tax_new,total_new
0,C004,South,Monitor,2,499,2026-01-01,998,79.84,1077.84,998,79.84,1077.84
1,C005,South,Tablet,5,499,2026-01-02,2495,199.60,2694.60,2495,199.60,2694.60
2,C003,North,Monitor,2,999,2026-01-03,1998,159.84,2157.84,1998,159.84,2157.84
3,C005,West,Monitor,4,999,2026-01-04,3996,319.68,4315.68,3996,319.68,4315.68
4,C005,North,Laptop,4,299,2026-01-05,1196,95.68,1291.68,1196,95.68,1291.68
5,C002,North,Tablet,4,1299,2026-01-06,5196,415.68,5611.68,5196,415.68,5611.68
6,C003,East,Laptop,4,1299,2026-01-07,5196,415.68,5611.68,5196,415.68,5611.68
7,C003,East,Tablet,5,499,2026-01-08,2495,199.60,2694.60,2495,199.60,2694.60
8,C003,East,Tablet,3,1299,2026-01-09,3897,311.76,4208.76,3897,311.76,4208.76
9,C005,South,Laptop,1,499,2026-01-10,499,39.92,538.92,499,39.92,538.92
10,C004,West,Laptop,4,299,2026-01-11,1196,95.68,1291.68,1196,95.68,1291.68
11,C003,West,Tablet,2,999,2026-01-12,1998,159.84,2157.84,1998,159.84,2157.84
12,C005,West,Phone,4,999,2026-01-13,3996,319.68,4315.68,3996,319.68,4315.68
13,C002,West,Monitor,2,999,2026-01-14,1998,159.84,2157.84,1998,159.84,2157.84
14,C004,East,Laptop,2,1299,2026-01-15,2598,207.84,2805.84,2598,207.84,2805.84
15,C002,South,Monitor,4,299,2026-01-16,1196,95.68,1291.68,1196,95.68,1291.68
16,C004,South,Phone,5,1299,2026-01-17,6495,519.60,7014.60,6495,519.60,7014.60
17,C005,East,Phone,2,1299,2026-01-18,2598,207.84,2805.84,2598,207.84,2805.84
18,C001,South,Phone,2,299,2026-01-19,598,47.84,645.84,598,47.84,645.84
19,C004,East,Laptop,4,299,2026-01-20,1196,95.68,1291.68,1196,95.68,1291.68

### Method chaining
- Homework to run

In [ ]:
result = (
    df
    .query("quantity >= 2")
    .assign(revenue=lambda x: x["quantity"] * x["price"])
    .groupby("region")
    .agg(total_revenue=("revenue", "sum"), average_revenue=("revenue", "mean"))
    .sort_values("total_revenue",ascending=False)
    .reset_index()
)

result

In [ ]:
customer_summary = (
    df.groupby("customer_id")
      .agg(
          total_revenue=("revenue", "sum"),
          average_order=("revenue", "mean"),
          orders=("revenue", "count"),
          last_purchase=("date", "max")
      )
      .reset_index()
)

customer_summary["revenue_pct"] = (
    customer_summary["total_revenue"] / customer_summary["total_revenue"].sum() * 100
)

top10 = (customer_summary.nlargest(10, "total_revenue"))

top10