### Lambda function?
- Lambda function is a small, anonymous function in python

In [1]:
# instead of writing a function like:

def square(n: int):
    return n * n

In [2]:
square(4)

16

### `lambda arguments: expression`

In [3]:
# we can instead write it this way:

square = lambda n: n * n

square(4)

16

In [5]:
doubler = lambda x: x * 2
doubler(4)

8

In [4]:
def doubler(x: int):
    return x * 2

doubler(4)

8

### Why use lambda functions?
- Lambda functions are useful when you need a small function for a short period of time
  especially when working with functions such as: `map(), filter(), sorted(), reduce()`, `pandas`
- Instead of defining a function separately, you can define it directly where you need it.

In [7]:
add = lambda x, y, z: x + y + z

add(4, 5, 8)

17

In [9]:
def add(x, y, z):
    return x + y + z

add(4, 5, 8)

17

### Lambda with `map()`
- `map()` applies a function to every item in a collection

In [12]:
# without lambda

numbers = [1, 2, 3, 4, 5]

def double(x):
    return x * 2

results = list(map(double, numbers))

print(results)

[2, 4, 6, 8, 10]

In [13]:
# with lambda

results = list(map(lambda x: x * 2, numbers))
print(results)

[2, 4, 6, 8, 10]

In [18]:
# without lambda function

names = ['john', 'alex', 'harrison']

def toUpper(name):
    return name.upper()

results = list(map(toUpper, names))
print(results)

['JOHN', 'ALEX', 'HARRISON']

In [19]:
# with lambda function

results = list(map(lambda name: name.upper(), names))
print(results)

['JOHN', 'ALEX', 'HARRISON']

### Lambda with `filter()`
- `filter()` keeps items that satisfy a condition

In [22]:
numbers = [1, 2, 3, 4, 5, 6]

def even(x):
    if x % 2 == 0:
        return x

results = list(filter(even, numbers))
print(results)

[2, 4, 6]

In [24]:
results = list(filter(lambda x: x % 2 == 0, numbers))
print(results)

[2, 4, 6]

In [25]:
names = ['john', 'alex', 'harrison']

results = list(filter(lambda x: x == 'alex', names))
print(results)

['alex']

### Lambda with `sorted()`

In [26]:
students = [
    ("John", 85),
    ("Alice", 95),
    ("Bob", 75),
    ("Mary", 90)
]
print(students)

[('John', 85), ('Alice', 95), ('Bob', 75), ('Mary', 90)]

In [41]:
# we want to sort the students by their score by ascending order : default

students[0][1]

students.sort(key=lambda student: student[1])

print(students)

[('Bob', 75), ('John', 85), ('Mary', 90), ('Alice', 95)]

In [43]:
# we want to sort the students by their score by descending order

students.sort(key=lambda student: student[1], reverse=True)

print(students)

[('Alice', 95), ('Mary', 90), ('John', 85), ('Bob', 75)]

### Lambda with Dictionaries

In [44]:
employees = [
    {"name": "John", "salary": 80000},
    {"name": "Alice", "salary": 95000},
    {"name": "Bob", "salary": 70000},
]

print(employees)

[{'name': 'John', 'salary': 80000}, {'name': 'Alice', 'salary': 95000}, {'name': 'Bob', 'salary': 70000}]

In [51]:
employees.sort(key=lambda employee: (employee['name'], employee['salary']), reverse=False)

for employee in employees:
    print(employee)

{'name': 'Alice', 'salary': 95000}
{'name': 'Bob', 'salary': 70000}
{'name': 'John', 'salary': 80000}

In [61]:
names = ["Christopher", "Bob", "Alexander", "John"]

names.sort(key=lambda name: len(name))

print(names)

['Bob', 'John', 'Alexander', 'Christopher']

### Lambda with Condition Expressions
- `lambda value: result_if_true if condition else result_if_false`

In [60]:
ages =  [1, 20, 13, 48, 50, 64, 77, 81, 95, 17]

check_age = lambda age: "Adult" if age >= 18 else "Minor"

list(map(check_age, ages))

['Minor',
 'Adult',
 'Minor',
 'Adult',
 'Adult',
 'Adult',
 'Adult',
 'Adult',
 'Adult',
 'Minor']

### Lambda + `map()` + `filter()`

In [66]:
# without lambda functions

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

def even(x):
    if x % 2 == 0:
        return x

def square(x):
    return x ** 2

even_numbers = filter(even, numbers)

squared = map(square, even_numbers)

print(list(squared))

[4, 16, 36, 64, 100]

In [67]:
# using lambda functions
even_numbers = filter(lambda x: x % 2 == 0, numbers)

squared = map(lambda x: x ** 2, even_numbers)

print(list(squared))

[4, 16, 36, 64, 100]

### Lambda + `reduce()`
- repeatedly applying a function to values

In [70]:
numbers = [1, 2, 3, 4, 5] # 15

In [69]:
from functools import reduce

In [73]:
def add(x, y):
    return x + y

# total = reduce(add, numbers)
total = reduce(lambda x, y: x + y, numbers)
print(total)

15

In [74]:
def multiply(x, y):
    return x * y

# total = reduce(multiply, numbers)
total = reduce(lambda x, y: x * y, numbers)
print(total)

120

### Lambda in Pandas

In [75]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Alice", "Bob", "John"],
    "score": [95, 75, 85]
})
df

    name  score
0  Alice     95
1    Bob     75
2   John     85

In [76]:
df["passed"] = df["score"].apply(lambda score: score >= 80)

print(df)

    name  score  passed
0  Alice     95    True
1    Bob     75   False
2   John     85    True

In [78]:
df["grade"] = df["score"].apply(lambda score: "A" if score >= 90 else "B" if score >= 80 else "C")
df

    name  score  passed grade
0  Alice     95    True     A
1    Bob     75   False     C
2   John     85    True     B

### Homework

In [80]:
# 1. find transactions greater than $1000, hint use lambda, filter, and for loop
# 2. now sort them by transaction amount.
# 3. extract only the transaction amounts
# 4. add 10% to every transaction amount.

transactions = [
    {"customer": "Alice", "amount": 500},
    {"customer": "Bob", "amount": 1200},
    {"customer": "John", "amount": 300},
    {"customer": "Mary", "amount": 2500},
]